name: test-gh

on:
  push:
jobs:
  test-all:
    name: Test GH - Linux
    runs-on: ubuntu-latest
    steps:
    - name: Run Tests
      run: |
        set -e -x
        docker run -d -p 5000:5000 --restart=always --name registry registry:2
        docker ps -a
        echo "-----------------------ROHIT-----------------"
